# Workflow name
name: Auto-PR workflow

# Controls when the action will run. 
on:
  # Triggers the workflow on push  only for the develop-restructur branch
  push:
    branches: [ develop-restructure ]


# This is a basic workflow that is manually triggered

jobs:
  createPullRequest:
    runs-on: ubuntu-latest
    steps:
      - name: Run the Action
        uses: devops-infra/action-pull-request@0.1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          target_branch: develop
          title: Automatated Pull Request
          body: "**Automated pull request**"
          label: auto-pr
